version: '3.7'
services:
  database:
    image: 'postgres:alpine'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DB}
    ports:
      - '${DB_PORT}:5432'
